### PR TITLE
import PARPACK from http://www.caam.rice.edu/software/ARPACK/

### PR DESCRIPTION
**Pull request by twmr**
this imports parpack96 and the corresponding patch for it into the
PARPACK directory. The software was downloaded on Thu Jan 12 2012.

Signed-off-by: Thomas Hisch thomas@opentech.at

### CODE REVIEW

**Comment by inducer** [comment]
Question: Is PARPACK a separate package? Or do you need the underlying ARPACK to build it?

**Comment by twmr** [comment]
You need the serial arpack code in order to build parpack

The website says: 
PARPACK (Parallel ARPACK) is an extension of the ARPACK software package 
used for ....

See the installation instructions for parpack: http://www.caam.rice.edu/software/ARPACK/SRC/instruction.parpack
There it is mentioned that parpack should be extracted into the arpack directory  (Not into a subdirectory of arpack as I did for this PR). During the parpack extraction process the Arpack Makefile gets overwritten. 

Note, I haven't used parpack yet, but I'm planning to use it.

**Comment by ViralBShah** [comment]
I do have a set of patches from Chao Yang for PARPACK beyond the ones that are on the Rice website. I will send them to you.

**Comment by inducer** [comment]
Sylvestre Ledru of http://forge.scilab.org/index.php/p/arpack-ng/ has asked me if I wanted to merge this effort with theirs, and I think that would make sense. They also already have PARPACK included.

**Comment by ViralBShah** [comment]
Yes, good idea.

-viral

**Comment by twmr** [comment]
+1

**Comment by twmr** [comment]
What is the state of the merge process ?

**Pull request closed without merging**
